#' Load sample names from VCF file
#'
#' @description
#' This function extract sample names from the VCF file. It is mandatory to compress the VCF file using bgzip and create an index using tabix.
#'
#'
#' @param file The VCF file.
#' @import Rsamtools
#' @return Sample names available in the VCF file.
#'
#' @export
vcf_sample = function(file){
  ### Check if vcf file and its index exist ###
  if(! file.exists(file)){
    stop("VCF file not found.")
  }
  if(! file.exists(paste0(file, ".tbi"))){
    stop("Index file not found. The index file should be generated by tabix and placed in the same folder as the vcf file.")
  }

  ### Load VCF header ###
  samples = as.character(Rsamtools::scanBcfHeader(file)[[file]]$Sample)
  return(samples)
}
